version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/cloudcart
      JWT_SECRET: supersecretkey
      PORT: 5001
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudcart
    ports:
      - "5432:5432"