apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: cloudkart-auth
          imagePullPolicy: Never

          ports:
            - containerPort: 5001

          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT

            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres-service:5432/cloudcart"