apiVersion: v1
kind: Service

metadata:
  name: auth-service

spec:
  type: ClusterIP

  selector:
    app: {{ .Values.auth.name }}

  ports:
    - protocol: TCP
      port: {{ .Values.auth.servicePort }}
      targetPort: {{ .Values.auth.containerPort }}