name: CloudKart CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Docker
        run: docker --version

      - name: Build Auth Image
        run: docker build -t cloudkart-auth ./auth-service

      - name: Build Frontend Image
        run: docker build -t cloudkart-frontend ./frontend